### ISSUE TITLE
No such file or directory for tmp_data/features/SylNet_out_files.tx on WSL 2

### ISSUE THREAD

**Issue by cvanpay** [orasanen/ALICE#1]
Using Ubuntu through WSL 2 on Windows Build 19041.

### Ubuntu Ver.

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

### Conda Ver.

```
     active environment : ALICE
    active env location : /home/craig/miniconda3/envs/ALICE
            shell level : 2
       user config file : /home/craig/.condarc
 populated config files :
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/craig/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/craig/miniconda3/pkgs
                          /home/craig/.conda/pkgs
       envs directories : /home/craig/miniconda3/envs
                          /home/craig/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.19.84-microsoft-standard ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Problem

SylNet works for each it, going through each feature extractor of CHI, MAL, KCHI, FEM, SPEECH, but when it is complete, this error occurs. Seems to be an error pointing to /tmp_data/features/SylNet_out_files.txt'. Could be specifically due to using WSL 2 and the PATH, but I'm not sure. Diarization output looks correct but no counts are given. Error 2 is probably related, as it couldn't find the out_files. 

### Error 1

```
SylNet completed
Traceback (most recent call last):
  File "extract_basic_features.py", line 10, in <module>
    with open(curdir + '/tmp_data/features/SylNet_out_files.txt') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Craig/ALICE/tmp_data/features/SylNet_out_files.txt'
paste: /mnt/c/Users/Craig/ALICE/tmp_data/features/SylNet_out.txt: No such file or directory
regress_ALUCs.py:10: UserWarning: genfromtxt: Empty input file: "/mnt/c/Users/Craig/ALICE/tmp_data/features/final_feats.txt"
  F = genfromtxt(curdir + "/tmp_data/features/final_feats.txt", delimiter='\t')
Traceback (most recent call last):
  File "regress_ALUCs.py", line 20, in <module>
    words_est = np.dot(F,X_words)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (0,2) and (5,) not aligned: 2 (dim 1) != 5 (dim 0)
paste: /mnt/c/Users/Craig/ALICE/tmp_data/features/SylNet_out_files.txt: No such file or directory
rm: cannot remove '/mnt/c/Users/Craig/ALICE/tmp_data/features/ALUCs_out_individual_tmp.txt': No such file or directory  getFinalEstimates.py:10: UserWarning: genfromtxt: Empty input file: "/mnt/c/Users/Craig/ALICE/tmp_data/features/ALUCs_out_individual.txt"
  F = genfromtxt(curdir + "/tmp_data/features/ALUCs_out_individual.txt", delimiter='\t')
ALICE completed. Results written to /mnt/c/Users/Craig/ALICE/ALICE_output.txt and /mnt/c/Users/Craig/ALICE/diarization_output.rttm.
```

### Error 2

```
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/mnt/c/Users/Craig/ALICE/SylNet/run_SylNet.py", line 86, in <module>
    raise Exception('Provided input file list does not exist.')
Exception: Provided input file list does not exist.
```

### Environment

```
# packages in environment at /home/craig/miniconda3/envs/ALICE:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
absl-py                   0.8.1                    py36_0    conda-forge
alembic                   1.3.3                    pypi_0    pypi
astor                     0.8.0                    py36_0
audioread                 2.1.8                    pypi_0    pypi
blas                      1.0                         mkl    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2020.1.1                      0
cachetools                4.0.0                    pypi_0    pypi
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2                   pypi_0    pypi
cliff                     2.18.0                   pypi_0    pypi
cmd2                      0.8.9                    pypi_0    pypi
colorlog                  4.1.0                    pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_0
cycler                    0.10.0                   pypi_0    pypi
dataclasses               0.7                      pypi_0    pypi
decorator                 4.4.1                    pypi_0    pypi
dlib                      19.19.0                  pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
gast                      0.2.2                      py_0    conda-forge
google-pasta              0.1.8                      py_0    conda-forge
grpcio                    1.16.1           py36hf8bcb03_1
h5py                      2.10.0           py36h7918eee_0
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
joblib                    0.14.1                   pypi_0    pypi
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
kiwisolver                1.1.0                    pypi_0    pypi
lame                      3.100             h14c3975_1001    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libopenblas               0.3.7                h5ec1e0e_7    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.11.2               h8b12597_0    conda-forge
librosa                   0.7.2                    pypi_0    pypi
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
llvmlite                  0.31.0                   pypi_0    pypi
mad                       0.15.1b              he1b5a44_0    conda-forge
mako                      1.1.1                    pypi_0    pypi
markdown                  3.1.1                      py_0    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.1.2                    pypi_0    pypi
mkl                       2020.0                      166    conda-forge
mpmath                    1.1.0                    pypi_0    pypi
munkres                   1.1.2                    pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                      pypi_0    pypi
numba                     0.48.0                   pypi_0    pypi
numpy                     1.17.5           py36h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
opt_einsum                3.1.0                      py_0    conda-forge
optuna                    1.0.0                    pypi_0    pypi
pandas                    1.0.0            py36hb3f55d8_0    conda-forge
pbr                       5.4.4                    pypi_0    pypi
pip                       20.0.2                     py_2    conda-forge
prettytable               0.7.2                    pypi_0    pypi
protobuf                  3.11.2                   pypi_0    pypi
pyannote-audio            0+unknown                pypi_0    pypi
pyannote-core             3.2                      pypi_0    pypi
pyannote-database         2.3.1                    pypi_0    pypi
pyannote-generators       2.0                      pypi_0    pypi
pyannote-metrics          2.0.2                    pypi_0    pypi
pyannote-pipeline         1.2                      pypi_0    pypi
pycparser                 2.19                     pypi_0    pypi
pyparsing                 2.4.6                    pypi_0    pypi
pyperclip                 1.7.0                    pypi_0    pypi
python                    3.6.7             h357f687_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                    pypi_0    pypi
python-speech-features    0.6                      pypi_0    pypi
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3                      pypi_0    pypi
readline                  8.0                  hf8c457e_0    conda-forge
resampy                   0.2.2                    pypi_0    pypi
scikit-learn              0.22.1                   pypi_0    pypi
scipy                     1.4.1            py36h921218d_0    conda-forge
setuptools                45.1.0                   py36_0    conda-forge
simplejson                3.17.0                   pypi_0    pypi
six                       1.14.0                   py36_0    conda-forge
sortedcollections         1.1.2                    pypi_0    pypi
sortedcontainers          2.1.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sox                       14.4.2            h27f72bc_1013    conda-forge
sqlalchemy                1.3.13                   pypi_0    pypi
sqlite                    3.30.1               hcee41ef_0    conda-forge
stevedore                 1.31.0                   pypi_0    pypi
sympy                     1.5.1                    pypi_0    pypi
tabulate                  0.8.6                    pypi_0    pypi
tensorboard               1.10.0                   pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tensorflow                1.10.1                   pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
torch                     1.4.0                    pypi_0    pypi
tqdm                      4.42.0                   pypi_0    pypi
typing                    3.7.4.1                  pypi_0    pypi
typing-extensions         3.7.4.1                  pypi_0    pypi
wcwidth                   0.1.8                    pypi_0    pypi
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.34.1                   py36_0    conda-forge
wrapt                     1.11.2           py36h516909a_0    conda-forge
xarray                    0.11.0                   pypi_0    pypi
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by cvanpay** [comment]
I built the env from git cloned to /home/user/ALICE within Linux rather than the mounted drive in Windows C and still receive the error.

```
SylNet completed
Traceback (most recent call last):
  File "extract_basic_features.py", line 10, in <module>
    with open(curdir + '/tmp_data/features/SylNet_out_files.txt') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/craig/ALICE/tmp_data/features/SylNet_out_files.txt'
paste: /home/craig/ALICE/tmp_data/features/SylNet_out.txt: No such file or directory
regress_ALUCs.py:10: UserWarning: genfromtxt: Empty input file: "/home/craig/ALICE/tmp_data/features/final_feats.txt"
  F = genfromtxt(curdir + "/tmp_data/features/final_feats.txt", delimiter='\t')
Traceback (most recent call last):
  File "regress_ALUCs.py", line 20, in <module>
    words_est = np.dot(F,X_words)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (0,2) and (5,) not aligned: 2 (dim 1) != 5 (dim 0)
paste: /home/craig/ALICE/tmp_data/features/SylNet_out_files.txt: No such file or directory
rm: cannot remove '/home/craig/ALICE/tmp_data/features/ALUCs_out_individual_tmp.txt': No such file or directory
getFinalEstimates.py:10: UserWarning: genfromtxt: Empty input file: "/home/craig/ALICE/tmp_data/features/ALUCs_out_individual.txt"
  F = genfromtxt(curdir + "/tmp_data/features/ALUCs_out_individual.txt", delimiter='\t')
ALICE completed. Results written to /home/craig/ALICE/ALICE_output.txt and /home/craig/ALICE/diarization_output.rttm.
```

**Comment by orasanen** [comment]
Hi! What kind of input files are you using? Can you also copy&paste the syntax you are using to call ALICE?

**Comment by cvanpay** [comment]
Hi, thanks for creating ALICE! Sorry for omitting that information.

I am using it on a folder "wavs" which includes 62 5 minute .wav files.

I am doing this with $ sh run_ALICE.sh wavs/

```
Found wav files.
Creating config for pyannote.
Done creating config for pyannote.
Extracting KCHI
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/home/craig//miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)
Test set: 0it [00:00, ?it/s]
```

It finds the files and works through each feature extractor of CHI, MAL, KCHI, FEM, SPEECH, but when it is complete, the above errors occur.

**Comment by cvanpay** [comment]
By the way, ALICE works very well on my macOS machine! But my PC is much more powerful, and this is the error I get when trying to run it on Windows 10 with my Windows Subsystem Linux 2 shell.

**Comment by orasanen** [comment]
Hmm, as you said, it could be a problem with Windows. We haven't actually done testing & debugging on that, but I forgot to add that it to the readme that ALICE has been so far confirmed to run on OSX and a couple of tested Linux variants.

Could you comment away the cleanup producedures at the end of run_ALICE.sh like this:

'''
#Cleanup
#rm -rf $THISDIR/tmp_data/
#cp $THISDIR/output_voice_type_classifier/tmp_data/all.rttm $THISDIR/diarization_output.rttm
#rm -rf $THISDIR/output_voice_type_classifier/

echo "ALICE completed. Results written to $THISDIR/ALICE_output.txt and $THISDIR/diarization_output.rttm."
'''

and then check whether /home/craig/ALICE/tmp_data/features/ folder exists at all after running run_ALICE.sh? Also, you could check if $THISDIR/tmp_data/short/ contains a list of .wav files, which should be the outputs from the diarization. There seems to be some kind of disconnect between diarizer writing to $THISDIR/tmp_data/short/ and SylNet trying to read from there.

**Comment by cvanpay** [comment]
Thanks for the suggestion!

Here's what happens after I do that. Note - I just ran it on a subset of 2 of the files to save time.

```
Found wav files.
Creating config for pyannote.
Done creating config for pyannote.
Extracting KCHI
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)
Test set: 2it [01:02, 31.31s/it]
Test set: 2it [00:01,  1.74it/s]
Extracting CHI
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)
Test set: 2it [01:02, 31.33s/it]
Test set: 2it [00:01,  1.64it/s]
Extracting MAL
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)
Test set: 2it [01:01, 30.57s/it]
Test set: 2it [00:01,  1.77it/s]
Extracting FEM
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)
Test set: 2it [01:00, 30.36s/it]
Test set: 2it [00:01,  1.54it/s]
Extracting SPEECH
Feature extractors based on "yaafe" are not available because "yaafelib" could not be found.
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/base.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  params_yml = yaml.load(fp)
Test set: 2it [01:05, 32.66s/it]
Test set: 2it [00:01,  1.71it/s]
SylNet completed
Traceback (most recent call last):
  File "extract_basic_features.py", line 10, in <module>
    with open(curdir + '/tmp_data/features/SylNet_out_files.txt') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/craig/ALICE/tmp_data/features/SylNet_out_files.txt'      paste: /home/craig/ALICE/tmp_data/features/SylNet_out.txt: No such file or directory
regress_ALUCs.py:10: UserWarning: genfromtxt: Empty input file: "/home/craig/ALICE/tmp_data/features/final_feats.txt"
  F = genfromtxt(curdir + "/tmp_data/features/final_feats.txt", delimiter='\t')
Traceback (most recent call last):
  File "regress_ALUCs.py", line 20, in <module>
    words_est = np.dot(F,X_words)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (0,2) and (5,) not aligned: 2 (dim 1) != 5 (dim 0)
paste: /home/craig/ALICE/tmp_data/features/SylNet_out_files.txt: No such file or directory
rm: cannot remove '/home/craig/ALICE/tmp_data/features/ALUCs_out_individual_tmp.txt': No such file or directory
getFinalEstimates.py:10: UserWarning: genfromtxt: Empty input file: "/home/craig/ALICE/tmp_data/features/ALUCs_out_individual.txt"
  F = genfromtxt(curdir + "/tmp_data/features/ALUCs_out_individual.txt", delimiter='\t')
ALICE completed. Results written to /home/craig/ALICE/ALICE_output.txt and /home/craig/ALICE/diarization_output.rttm.
```

That folder does exist - and Sylnet_Out_Files.txt exists.

```
/home/craig/ALICE/tmp_data/short/a2_00000100_00002630.wav
/home/craig/ALICE/tmp_data/short/a2_00005910_00054930.wav
/home/craig/ALICE/tmp_data/short/a2_00068340_00075160.wav
/home/craig/ALICE/tmp_data/short/a2_00075330_00108400.wav
/home/craig/ALICE/tmp_data/short/a2_00111390_00130040.wav
... plus more
```

Sylnet_Out.txt also exists.

```
1
8
2
2
5
2
1
1
1
... plus more
```
And 

$THISDIR/tmp_data/short/ has the files listed in Sylnet_Out.txt

additionally, this is the second error again, if it helps:

```
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/craig/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
DATA LOADING DONE
2020-02-27 07:01:35.693803: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/craig/ALICE/tmp_data/features/SylNet_out.txt
```

**Comment by cvanpay** [comment]
I spent a lot of time working on this, but I think it is just an artifact of WSL2 in beta. Perhaps I will try again when support has increased for it. I've tested and gotten the script running on MacOS and Manjaro (Arch Linux). Additionally, I got the cuda option working on Arch Linux and it works fantastically. Processes around 1.75 seconds per 5 minute segment (each feature) !

**Comment by orasanen** [comment]
@cvanpay Thank you so much for looking into this! This is very useful! I also apologize that the response has been slow at our end. I still think we need to look into the Windows compatibility in a broader sense. For now, I will add a note to the readme that Linux + OSX support exists, while Windows is not fully tested.

**Comment by cvanpay** [comment]
@orasanen it was my pleasure, thank you for making this tool! No worries about communication, it was kind of me trying to fit a round peg in a square hole. I have tested it and it has worked on both Ubuntu and Manjaro, with --gpu and without! So you can add that to the list of Linux distros you've tested on. I will probably try again as WSL2 gets broad release (it's only open for Windows Insiders right now) and when it has access to GPU (even if I did get it working, it can't access GPU so it was really limited anyway). Works very well on CPU - was processing around 30 sec/5 min/feature, but really shines on GPU.
