### ISSUE TITLE
PyAnnote problem on Linux VM 

### ISSUE THREAD

**Issue by orasanen** [orasanen/ALICE#27]
This happens on "Linux VM on an older MacBook (before the M series processors)":

(ALICE) brandt.5sa@vm-ehtvm4w0l92p:~/ALICE$ sh run_ALICE.sh ~/10-min-sample-16khz.wav 
Creating config for pyannote.
Done creating config for pyannote.
Traceback (most recent call last):
  File "/home/brandt.5sa/miniconda3/envs/ALICE/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/pyannote_audio.py", line 307, in main
    from .labels_detection import MultilabelDetection
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/labels_detection.py", line 39, in <module>
    from pyannote.audio.applications.base import create_zip
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/pyannote/audio/applications/base.py", line 48, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 13, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/plugins/histogram/summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/plugins/histogram/summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 25, in <module>
    from . import app  # noqa
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/app.py", line 21, in <module>
    from . import flags
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/flags.py", line 25, in <module>
    from absl.flags import *  # pylint: disable=wildcard-import
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/home/brandt.5sa/miniconda3/envs/ALICE/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
Something went wrong when applying the model
Aborting.
Traceback (most recent call last):
  File "split_to_utterances.py", line 15, in <module>
    with open(curdir + '/output_voice_type_classifier/tmp_data/all.rttm') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/brandt.5sa/ALICE/output_voice_type_classifier/tmp_data/all.rttm'
getFinalEstimates.py:10: UserWarning: genfromtxt: Empty input file: "/home/brandt.5sa/ALICE/tmp_data/features/ALUCs_out_individual.txt"
  F = genfromtxt(curdir + "/tmp_data/features/ALUCs_out_individual.txt", delimiter='\t')
cp: cannot stat '/home/brandt.5sa/ALICE/output_voice_type_classifier/tmp_data/all.rttm': No such file or directory
ALICE completed. Results written to /home/brandt.5sa/ALICE/ALICE_output.txt and /home/brandt.5sa/ALICE/diarization_output.rttm.

**Comment by MarvinLvn** [comment]
Should be solved by PR https://github.com/orasanen/ALICE/pull/28

**Comment by MarvinLvn** [comment]
Closing this!
To anyone: feel free to reopen if the issue reappears!
